### ISSUE TITLE
audience-meter KO since socket.io v0.7

### ISSUE THREAD

**Issue by XavM** [rs/audience-meter#1]
audience-meter KO since socket.io v0.7

Please see https://github.com/LearnBoost/Socket.IO/wiki/Migrating-0.6-to-0.7+

Should change audience-meter.js  -> 

Line 92 :

```
BEFORE: 
    client.send(info);
AFTER :
    client.json.send(info);
```

Not sure about this one - Line 138 :

```
BEFORE:
   listener.send(listener.bufferNotif);
AFTER:
    listener.json.send(listener.bufferNotif);
```

Line 206 : 

```
BEFORE: 
    socket.on('connection', function(client)
AFTER : 
    socket.sockets.on('connection', function(client)
```

Should change demo.html lines 6 to 7 -> 

```
BEFORE: 
    var socket = new io.Socket("{hostname}");
    socket.connect();
AFTER : 
    var socket = io.connect("http://{hostname}");
```

**Comment by rs** [comment]
It was a bit more complicated than that but it's done in 0f853a1577a6e98be449d476e4554690cc69ff1e.
Be careful, the client side code isn't backward compat.
